### ISSUE TITLE
When closing chat screen, error saying "cannot read properties of null" appears

### ISSUE THREAD

**Issue by BlackStone8960** [BlackStone8960/Musician-First#89]
When closing chat screen, following error appears. 

<img width="419" alt="Screen Shot 2021-11-15 at 5 42 47 PM" src="https://user-images.githubusercontent.com/60183777/141880554-28e6bddd-66a4-4ee9-a2df-5f2573b8577f.png">

**Comment by Kit486759** [comment]
**Reason of error:** 
When turning on the chatbox, then scroll event listener was added. When closing the chatbox, that listener is still there but the element in DOM is already unmounted that's why return error property is null.
**Fix:**
Added function to close that event listener when closing the chatbox.

**Comment by BlackStone8960** [comment]
That makes sense. Thank you for the explanation.
